//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balda {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balda.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        public static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balda.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current game will be lost. Continue?.
        /// </summary>
        public static string cfDemoText {
            get {
                return ResourceManager.GetString("cfDemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstration.
        /// </summary>
        public static string cfDemoTitle {
            get {
                return ResourceManager.GetString("cfDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really want restart game?.
        /// </summary>
        public static string cfRestartText {
            get {
                return ResourceManager.GetString("cfRestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string cfRestartTitle {
            get {
                return ResourceManager.GetString("cfRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game.
        /// </summary>
        public static string dCurrent {
            get {
                return ResourceManager.GetString("dCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete checked.
        /// </summary>
        public static string dDel {
            get {
                return ResourceManager.GetString("dDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send dictionary to developer.
        /// </summary>
        public static string dSend {
            get {
                return ResourceManager.GetString("dSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string dUserDict {
            get {
                return ResourceManager.GetString("dUserDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put new letter near existing, and select word containing it.
        /// </summary>
        public static string fcfNearText {
            get {
                return ResourceManager.GetString("fcfNearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put letters near others.
        /// </summary>
        public static string fcfNearTitle {
            get {
                return ResourceManager.GetString("fcfNearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play again.
        /// </summary>
        public static string fgAgain {
            get {
                return ResourceManager.GetString("fgAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save it to dictionary?.
        /// </summary>
        public static string fgcfAddText {
            get {
                return ResourceManager.GetString("fgcfAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word not in dictionary.
        /// </summary>
        public static string fgcfAddTitle {
            get {
                return ResourceManager.GetString("fgcfAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use words more than once.
        /// </summary>
        public static string fgcfUsedText {
            get {
                return ResourceManager.GetString("fgcfUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word already used in the game.
        /// </summary>
        public static string fgcfUsedTitle {
            get {
                return ResourceManager.GetString("fgcfUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie game.
        /// </summary>
        public static string fgDraw {
            get {
                return ResourceManager.GetString("fgDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss a turn.
        /// </summary>
        public static string fgMiss {
            get {
                return ResourceManager.GetString("fgMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: .
        /// </summary>
        public static string fgPlayer {
            get {
                return ResourceManager.GetString("fgPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: .
        /// </summary>
        public static string fgScore {
            get {
                return ResourceManager.GetString("fgScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string fgWinner {
            get {
                return ResourceManager.GetString("fgWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string fgWScore {
            get {
                return ResourceManager.GetString("fgWScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single player.
        /// </summary>
        public static string gm1 {
            get {
                return ResourceManager.GetString("gm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two players (hotseat).
        /// </summary>
        public static string gm2 {
            get {
                return ResourceManager.GetString("gm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string hdEasy {
            get {
                return ResourceManager.GetString("hdEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        public static string hdFull {
            get {
                return ResourceManager.GetString("hdFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string hdHard {
            get {
                return ResourceManager.GetString("hdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string hdMedium {
            get {
                return ResourceManager.GetString("hdMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game starts with a 5x5 square table with a 5 letter word written in the middle row..
        /// </summary>
        public static string hp0 {
            get {
                return ResourceManager.GetString("hp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each turn one of the players adds one letter and determines a sequence of letters from the table (including the new one) without repetitions which represent a word..
        /// </summary>
        public static string hp1 {
            get {
                return ResourceManager.GetString("hp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new word must be a noun and must not be a form of any of ones appeared earlier..
        /// </summary>
        public static string hp2 {
            get {
                return ResourceManager.GetString("hp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player increases its score for the number of letters in the word..
        /// </summary>
        public static string hp3 {
            get {
                return ResourceManager.GetString("hp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string mGame {
            get {
                return ResourceManager.GetString("mGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mmAbout {
            get {
                return ResourceManager.GetString("mmAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstration.
        /// </summary>
        public static string mmDemo {
            get {
                return ResourceManager.GetString("mmDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game rules.
        /// </summary>
        public static string mmHelp {
            get {
                return ResourceManager.GetString("mmHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string mmRestart {
            get {
                return ResourceManager.GetString("mmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My scoreboard.
        /// </summary>
        public static string mmScore {
            get {
                return ResourceManager.GetString("mmScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string mmScoreboard {
            get {
                return ResourceManager.GetString("mmScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mmSettings {
            get {
                return ResourceManager.GetString("mmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string mWords {
            get {
                return ResourceManager.GetString("mWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string pgSettings {
            get {
                return ResourceManager.GetString("pgSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string plFriend {
            get {
                return ResourceManager.GetString("plFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string plYou {
            get {
                return ResourceManager.GetString("plYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase and remove banner.
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest word.
        /// </summary>
        public static string sbLongestWord {
            get {
                return ResourceManager.GetString("sbLongestWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string sbScore {
            get {
                return ResourceManager.GetString("sbScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string stHardness {
            get {
                return ResourceManager.GetString("stHardness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game language.
        /// </summary>
        public static string stLang {
            get {
                return ResourceManager.GetString("stLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        public static string stMode {
            get {
                return ResourceManager.GetString("stMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field size.
        /// </summary>
        public static string stSize {
            get {
                return ResourceManager.GetString("stSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string stUn1 {
            get {
                return ResourceManager.GetString("stUn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second player name.
        /// </summary>
        public static string stUn2 {
            get {
                return ResourceManager.GetString("stUn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string tPhone {
            get {
                return ResourceManager.GetString("tPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select side neighbour cells to make word, than tap selected letter again to confirm word.
        /// </summary>
        public static string wbNearText {
            get {
                return ResourceManager.GetString("wbNearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters must be neighbours by side.
        /// </summary>
        public static string wbNearTitle {
            get {
                return ResourceManager.GetString("wbNearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use added letter in your word.
        /// </summary>
        public static string wbUnusedNewText {
            get {
                return ResourceManager.GetString("wbUnusedNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New letter isn&apos;t used!.
        /// </summary>
        public static string wbUnusedNewTitle {
            get {
                return ResourceManager.GetString("wbUnusedNewTitle", resourceCulture);
            }
        }
    }
}
